import { readFileSync } from 'node:fs'
import { join } from 'node:path'

interface ToolText { name: string; description: string; synonyms: string[]; privacyNote?: string }
interface GuideText { title: string; summary: string; intro: string; steps: { title: string; detail: string }[]; tips: string[]; notes: string[] }
export interface CatalogTool { id: string; slug: string; status: string; noFile: boolean; categories: string[]; text: Record<string, ToolText> }
interface CatalogGuide { slug: string; toolIds: string[]; text: Record<string, GuideText> }
interface Catalog { locales: string[]; tools: CatalogTool[]; guides: CatalogGuide[] }

let cached: Catalog | null = null

/** Generated by frontend/scripts/export-tool-catalog.mjs; resolved from dist/mcp/. */
export function toolCatalog(): Catalog {
  cached ??= JSON.parse(readFileSync(join(__dirname, '..', '..', 'data', 'tool-catalog.json'), 'utf8')) as Catalog
  return cached
}

export function readyTool(slug: string) {
  return toolCatalog().tools.find((tool) => tool.slug === slug && tool.status === 'ready') ?? null
}

/** Asked language first, then English, then Vietnamese (the source language, always complete). */
export function textFor<T>(text: Record<string, T>, locale: string | undefined): T | null {
  return (locale ? text[locale] : undefined) ?? text.en ?? text.vi ?? null
}

const fold = (value: string) => value.toLowerCase().normalize('NFD').replace(/\p{M}/gu, '').replace(/đ/g, 'd')
const words = (value: string) => fold(value).split(/[^\p{L}\p{N}]+/u).filter((word) => word.length > 1)

/**
 * Plain keyword scoring over name, synonyms and description in the asked language plus Vietnamese and
 * English. The model reads the descriptions and picks; the site's intent search is not repeated here.
 */
export function findTools(query: string, locale: string | undefined, limit: number) {
  const terms = [...new Set(words(query.slice(0, 500)))]
  const ready = toolCatalog().tools.filter((tool) => tool.status === 'ready')
  const scored = ready.map((tool) => {
    let score = 0
    for (const code of new Set([locale ?? 'vi', 'vi', 'en'])) {
      const text = tool.text[code]
      if (!text) continue
      const name = words(text.name)
      const synonyms = text.synonyms.flatMap(words)
      const description = words(text.description)
      for (const term of terms) {
        const hit = (list: string[]) => list.some((word) => word === term || (term.length >= 3 && word.startsWith(term)))
        if (hit(name)) score += 3
        else if (hit(synonyms)) score += 2
        else if (hit(description)) score += 1
      }
    }
    return { tool, score }
  })
  const picked = terms.length ? scored.filter((entry) => entry.score > 0).sort((a, b) => b.score - a.score) : scored
  return picked.slice(0, limit).map(({ tool }) => {
    const text = textFor(tool.text, locale)
    return { slug: tool.slug, name: text?.name ?? tool.id, description: text?.description ?? '', needsFile: !tool.noFile }
  })
}

export function toolGuide(slug: string, locale: string | undefined) {
  const tool = readyTool(slug)
  if (!tool) return null
  const text = textFor(tool.text, locale)
  const guides = toolCatalog().guides.filter((guide) => guide.toolIds.includes(tool.id)).map((guide) => textFor(guide.text, locale)).filter(Boolean)
  return {
    slug: tool.slug, name: text?.name ?? tool.id, description: text?.description ?? '', needsFile: !tool.noFile,
    // Free tools run in the browser; the note says what, if anything, leaves the device.
    privacy: text?.privacyNote ?? 'Chạy ngay trong trình duyệt; tệp không rời máy người dùng.',
    guides,
  }
}
