import type { ToolDefinition } from '../types/tool.types'

/**
 * Mọi công cụ của "Chuyện Nhỏ", theo đúng thứ tự trên lưới "tất cả".
 *
 * Mô tả phải nói ĐÚNG việc công cụ làm được hôm nay (OCR chỉ có tiếng Việt,
 * chuyển đổi ảnh không có HEIC) — thẻ hứa quá tay là người dùng thả tệp vào rồi
 * mới biết. Công cụ chưa làm mang `status: 'soon'`: có thẻ, không có đường vào.
 *
 * Bốn slug `ghep-pdf` · `tach-pdf` · `anh-sang-pdf` · `pdf-sang-word` đã phát
 * ra ngoài từ trước khi có trang này — không đổi.
 *
 * Tệp này CHỈ được có `import type`: plugin `shareMeta` (vite.config.ts) bỏ kiểu
 * rồi nạp nó bằng Node lúc build để sinh thẻ chia sẻ — một import chạy thật
 * (alias `@/`, đường dẫn không đuôi) là build vỡ. Thứ cần import nằm ở `tool-catalog.ts`.
 */
export const ALL_TOOLS: ToolDefinition[] = [
  {
    id: 'scan-to-pdf',
    slug: 'anh-sang-pdf',
    name: 'Scan ảnh → PDF',
    description: 'Gộp ảnh chụp thành một tệp PDF',
    icon: 'camera',
    categories: ['document', 'image'],
    priority: 1,
    synonyms: ['jpg sang pdf', 'ảnh thành pdf', 'chụp tài liệu', 'image to pdf', 'ghép ảnh'],
    pageTitle: 'Chuyển ảnh sang PDF miễn phí',
    status: 'ready',
    screen: 'images-to-pdf',
  },
  {
    id: 'merge-pdf',
    slug: 'ghep-pdf',
    name: 'Ghép PDF',
    description: 'Gộp nhiều tệp PDF thành một',
    icon: 'files',
    categories: ['document'],
    priority: 2,
    synonyms: ['nối pdf', 'gộp pdf', 'kết hợp', 'merge'],
    status: 'ready',
    screen: 'merge-pdf',
  },
  {
    id: 'split-pdf',
    slug: 'tach-pdf',
    name: 'Tách PDF',
    description: 'Tách trang, trích trang ra tệp riêng',
    icon: 'scissors',
    categories: ['document'],
    priority: 3,
    synonyms: ['cắt pdf', 'chia pdf', 'lấy trang', 'split'],
    status: 'ready',
    screen: 'split-pdf',
  },
  {
    id: 'compress-pdf',
    slug: 'nen-pdf',
    name: 'Nén PDF',
    description: 'Giảm dung lượng tệp PDF',
    icon: 'file-earmark-zip',
    categories: ['document'],
    priority: 4,
    synonyms: ['thu nhỏ pdf', 'pdf nhẹ', 'compress'],
    status: 'ready',
    screen: 'compress-pdf',
  },
  {
    id: 'convert-file',
    slug: 'pdf-sang-word',
    name: 'Chuyển đổi file',
    description: 'PDF sang Word, Excel, ảnh',
    icon: 'arrow-left-right',
    categories: ['document'],
    priority: 6,
    synonyms: ['pdf to word', 'docx', 'xlsx', 'pdf sang excel', 'pdf sang jpg', 'pdf sang ảnh'],
    pageTitle: 'Chuyển PDF sang Word miễn phí',
    status: 'ready',
    screen: 'convert-file',
  },
  {
    id: 'pdf-to-image',
    slug: 'pdf-sang-anh',
    name: 'PDF → Ảnh',
    description: 'Mỗi trang PDF thành một ảnh JPG, PNG',
    icon: 'image',
    categories: ['document', 'image'],
    synonyms: ['pdf sang jpg', 'pdf sang png', 'pdf to jpg', 'xuất ảnh'],
    status: 'ready',
    screen: 'pdf-to-image',
  },
  {
    id: 'organize-pdf',
    slug: 'sap-xep-pdf',
    name: 'Sắp xếp PDF',
    description: 'Đổi thứ tự, xoay, bỏ trang',
    icon: 'grid-3x3-gap',
    categories: ['document'],
    synonyms: ['đảo trang', 'xoay trang', 'xoá trang', 'sắp lại trang'],
    status: 'ready',
    screen: 'organize-pdf',
  },
  {
    id: 'page-numbers',
    slug: 'danh-so-trang',
    name: 'Đánh số trang',
    description: 'Thêm số trang vào tệp PDF',
    icon: 'hash',
    categories: ['document'],
    synonyms: ['số trang', 'page number', 'chân trang'],
    status: 'ready',
    screen: 'page-numbers',
  },
  {
    id: 'stamp-pdf',
    slug: 'dong-dau-pdf',
    name: 'Đóng dấu PDF',
    description: 'Dấu chữ hoặc logo lên các trang',
    icon: 'droplet-half',
    categories: ['document'],
    synonyms: ['watermark', 'logo', 'bản sao', 'chèn dấu'],
    status: 'ready',
    screen: 'stamp-pdf',
  },
  {
    id: 'redact-pdf',
    slug: 'che-thong-tin-pdf',
    name: 'Che thông tin PDF',
    description: 'Xoá hẳn vùng nhạy cảm khỏi tệp',
    icon: 'eye-slash',
    categories: ['document'],
    synonyms: ['bôi đen', 'redact', 'ẩn thông tin', 'xoá chữ'],
    status: 'ready',
    screen: 'redact-pdf',
  },
  {
    id: 'view-pdf',
    slug: 'xem-pdf',
    name: 'Xem PDF',
    description: 'Xem, tìm chữ, ghi chú trên trang',
    icon: 'file-earmark-pdf',
    categories: ['document'],
    processing: 'browser-model',
    synonyms: ['đọc pdf', 'mở pdf'],
    status: 'ready',
    screen: 'editor',
  },
  {
    id: 'ocr',
    slug: 'ocr-van-ban',
    name: 'OCR văn bản',
    description: 'Nhận dạng chữ tiếng Việt trên bản scan',
    icon: 'textarea-t',
    categories: ['document', 'image'],
    processing: 'browser-model',
    priority: 7,
    synonyms: ['nhận diện chữ', 'pdf tìm được chữ', 'searchable'],
    status: 'ready',
    screen: 'ocr',
  },
  {
    id: 'compare',
    slug: 'so-sanh-tai-lieu',
    name: 'So sánh tài liệu',
    description: 'So chữ hai bản PDF, chỉ ra dòng khác',
    icon: 'layout-split',
    categories: ['document'],
    synonyms: ['đối chiếu', 'diff', 'so sánh pdf', 'khác nhau', 'bản cũ bản mới'],
    status: 'ready',
    screen: 'compare-pdf',
  },
  {
    id: 'sign',
    slug: 'ky-tai-lieu',
    name: 'Chèn chữ ký',
    description: 'Vẽ tay hoặc chèn ảnh chữ ký lên trang',
    icon: 'pen',
    categories: ['document'],
    synonyms: ['ký tài liệu', 'ký tên', 'chữ ký', 'ký pdf', 'sign'],
    status: 'ready',
    screen: 'sign-pdf',
  },
  {
    id: 'edit-pdf',
    slug: 'chinh-sua-pdf',
    name: 'Chỉnh sửa PDF',
    description: 'Sửa chữ, đánh dấu, sắp xếp trang',
    icon: 'pencil-square',
    categories: ['document'],
    processing: 'browser-model',
    priority: 5,
    synonyms: ['sửa pdf', 'xoay trang', 'xoá trang', 'thêm chữ'],
    status: 'ready',
    screen: 'editor',
  },
  {
    id: 'image-to-text',
    slug: 'anh-sang-van-ban',
    name: 'Ảnh → Văn bản',
    description: 'Lấy chữ tiếng Việt từ ảnh chụp',
    icon: 'card-text',
    categories: ['image', 'document'],
    processing: 'browser-model',
    synonyms: ['ocr ảnh', 'chép chữ từ ảnh', 'trích chữ', 'image to text'],
    status: 'ready',
    screen: 'image-to-text',
  },
  {
    id: 'measure-image',
    slug: 'do-kich-thuoc-anh',
    name: 'Đo kích thước ảnh',
    description: 'Đo chiều dài, diện tích trên ảnh',
    icon: 'rulers',
    categories: ['image', 'calc'],
    synonyms: ['thước đo', 'đo bản vẽ', 'tỉ lệ'],
    status: 'ready',
    screen: 'measure-image',
  },
  {
    id: 'convert-image',
    slug: 'chuyen-doi-anh',
    name: 'Chuyển đổi ảnh',
    description: 'Đổi giữa JPG, PNG, WebP',
    icon: 'images',
    categories: ['image'],
    priority: 9,
    synonyms: ['đổi đuôi ảnh', 'png sang jpg', 'jpg sang png', 'webp sang jpg'],
    status: 'ready',
    screen: 'convert-image',
  },
  {
    id: 'compress-image',
    slug: 'nen-anh',
    name: 'Nén ảnh',
    description: 'Giảm dung lượng ảnh',
    icon: 'file-earmark-image',
    categories: ['image'],
    priority: 8,
    synonyms: ['thu nhỏ ảnh', 'ảnh nhẹ', 'resize'],
    status: 'ready',
    screen: 'compress-image',
  },
  {
    id: 'crop-image',
    slug: 'cat-chinh-anh',
    name: 'Cắt & chỉnh ảnh',
    description: 'Cắt, xoay, chỉnh sáng tối',
    icon: 'crop',
    categories: ['image'],
    synonyms: ['crop', 'xoay ảnh', 'lật ảnh', 'độ sáng'],
    status: 'ready',
    screen: 'crop-image',
  },
  {
    id: 'batch-image',
    slug: 'anh-hang-loat',
    name: 'Ảnh hàng loạt',
    description: 'Đổi cỡ, đổi tên, đổi định dạng cả lô',
    icon: 'collection',
    categories: ['image'],
    synonyms: ['resize ảnh', 'đổi tên ảnh', 'thu nhỏ ảnh', 'batch', 'nhiều ảnh'],
    status: 'ready',
    screen: 'batch-image',
  },
  {
    id: 'mark-image',
    slug: 'che-dong-dau-anh',
    name: 'Che & đóng dấu ảnh',
    description: 'Che thông tin, đóng dấu chữ lên ảnh',
    icon: 'eye-slash',
    categories: ['image'],
    synonyms: ['watermark', 'bôi đen', 'che mặt', 'che số', 'đóng dấu bản quyền'],
    status: 'ready',
    screen: 'mark-image',
  },
  {
    id: 'id-photo',
    slug: 'anh-the',
    name: 'Ảnh thẻ & In ảnh',
    description: 'Cắt ảnh thẻ, xếp nhiều bản lên tờ in',
    icon: 'person-badge',
    categories: ['image'],
    synonyms: ['ảnh 3x4', 'ảnh 4x6', 'ảnh hộ chiếu', 'in ảnh thẻ', 'passport'],
    status: 'ready',
    screen: 'id-photo',
  },
  {
    id: 'qr-create',
    slug: 'tao-ma-qr',
    name: 'Tạo QR Code',
    description: 'Tạo mã QR từ chữ hoặc đường dẫn',
    icon: 'qr-code',
    categories: ['data'],
    priority: 10,
    synonyms: ['mã qr', 'qr link'],
    status: 'ready',
    screen: 'qr-create',
    noFile: true,
  },
  {
    id: 'barcode-create',
    slug: 'tao-ma-vach',
    name: 'Tạo mã vạch',
    description: 'EAN-13, Code 128, ITF-14 — một mã hoặc cả lô',
    icon: 'upc',
    categories: ['data'],
    synonyms: ['barcode', 'mã vạch', 'ean', 'code 128', 'code 39', 'itf', 'in tem', 'mã vật tư'],
    status: 'ready',
    screen: 'barcode-create',
    noFile: true,
  },
  {
    id: 'qr-read',
    slug: 'doc-ma-qr',
    name: 'Đọc mã QR/Barcode',
    description: 'Quét mã từ ảnh hoặc camera',
    icon: 'qr-code-scan',
    categories: ['data'],
    synonyms: ['quét qr', 'scan qr', 'mã vạch'],
    status: 'ready',
    screen: 'qr-read',
  },
  {
    id: 'quick-calc',
    slug: 'tinh-toan-nhanh',
    name: 'Tính toán nhanh',
    description: 'Diện tích, thể tích, khối lượng',
    icon: 'calculator',
    categories: ['calc'],
    priority: 11,
    synonyms: ['máy tính', 'm2', 'm3', 'bê tông'],
    status: 'ready',
    screen: 'quick-calc',
    noFile: true,
  },
  {
    id: 'money-calc',
    slug: 'tinh-tien',
    name: 'Tính tiền & thuế',
    description: 'Phần trăm, VAT, chiết khấu, lãi gộp, chia tiền',
    icon: 'cash-coin',
    categories: ['money'],
    synonyms: ['vat', 'thuế gtgt', 'phần trăm', 'giảm giá', 'margin', 'markup', 'chia hoá đơn', 'lợi nhuận'],
    status: 'ready',
    screen: 'money-calc',
    noFile: true,
  },
  {
    id: 'date-calc',
    slug: 'tinh-ngay',
    name: 'Tính ngày & thời hạn',
    description: 'Đếm ngày, ngày làm việc, cộng trừ ngày',
    icon: 'calendar-check',
    categories: ['date'],
    synonyms: ['đếm ngày', 'hạn chót', 'deadline', 'ngày làm việc', 'bao nhiêu ngày'],
    status: 'ready',
    screen: 'date-calc',
    noFile: true,
  },
  {
    id: 'house-orientation',
    slug: 'huong-nha-la-ban',
    name: 'Hướng nhà & la bàn',
    description: 'Đo hướng nhà, đặt la bàn lên ảnh, bản vẽ',
    icon: 'compass',
    categories: ['home'],
    synonyms: ['la bàn', 'xem hướng nhà', 'hướng cửa', 'phong thuỷ', 'bát trạch', 'hướng mặt tiền', 'nắng chiều'],
    status: 'ready',
    screen: 'house-orientation',
  },
  {
    id: 'quick-note',
    slug: 'ghi-chu-nhanh',
    name: 'Ghi chú nhanh',
    description: 'Ghi chú, danh sách việc lưu trên máy',
    icon: 'journal-check',
    categories: ['other'],
    synonyms: ['note', 'todo', 'việc cần làm'],
    status: 'ready',
    screen: 'quick-note',
    noFile: true,
  },
  {
    id: 'char-count',
    slug: 'dem-ky-tu',
    name: 'Đếm ký tự',
    description: 'Đếm chữ, từ, dòng',
    icon: 'fonts',
    categories: ['document'],
    synonyms: ['đếm từ', 'word count', 'số chữ'],
    status: 'ready',
    screen: 'char-count',
    noFile: true,
  },
  {
    id: 'unit-convert',
    slug: 'chuyen-doi-don-vi',
    name: 'Chuyển đổi đơn vị',
    description: 'Chiều dài, diện tích, khối lượng',
    icon: 'arrow-repeat',
    categories: ['calc'],
    priority: 12,
    synonyms: ['đổi đơn vị', 'inch', 'feet', 'mét'],
    status: 'ready',
    screen: 'unit-convert',
    noFile: true,
  },
  {
    id: 'color',
    slug: 'mau-sac',
    name: 'Màu sắc',
    description: 'Chọn màu, đổi mã màu',
    icon: 'palette',
    categories: ['image'],
    synonyms: ['bảng màu', 'hex', 'rgb'],
    status: 'ready',
    screen: 'color',
    noFile: true,
  },
  {
    id: 'random-code',
    slug: 'tao-ma-ngau-nhien',
    name: 'Tạo mã ngẫu nhiên',
    description: 'Mật khẩu, mã đơn, mã phiếu',
    icon: 'shuffle',
    categories: ['data'],
    synonyms: ['password', 'sinh mã', 'ngẫu nhiên'],
    status: 'ready',
    screen: 'random-code',
    noFile: true,
  },
]
